"""empty message

Revision ID: 311cd47f372b
Revises: 
Create Date: 2024-02-06 21:38:02.835272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311cd47f372b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('raciones', sa.Integer(), nullable=True),
    sa.Column('tiempo', sa.Integer(), nullable=True),
    sa.Column('pasos', sa.String(length=1000), nullable=True),
    sa.Column('es_publicada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas')
    # ### end Alembic commands ###
